sudo: required
services:
  - docker
before_install:
  - docker pull busybox
  - echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin
script:
  - docker build -t cjy632258/frp .
  - docker build -t cjy632258/frp:client -f client/Dockerfile .

after_success:
  - docker push cjy632258/frp
